### ISSUE TITLE
Core UI - Page Layout

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/bexis2-core-ui#43]
Inhaltliche Beschreibung: siehe unten

# ToDos

## Header 
- [x] erstelle eine default header html (absprache mit sven wo die dateien abgelegt werden sollen, eventl in den tenants)
- [x] lade die default header html vom backend und rendere sie in der Page-Componente
- [x]  Menu -> Logo und Menu auf einer Zeile, wenn das logo nicht mit kommt, dann muss das menu direkt vorne anfangen
- [x] Load menu data via pageload, not on mount (+page.js)  (ask david)

## Breadcrumb / Trennbalken
_Comment FZ: in PlantHub hab ich schon Breadcrumb implementiert, man könnte sich daran orientieren_
_Generelle Funktionsweise: https://www.skeleton.dev/elements/breadcrumbs_

### Schwarzer Trennbalken:
- [x] entfernen des Textes in dem schwarzen Balken (Core)
- [x] Balken muss schmaler werden (Core)
- [x] Trennbalken zwischen Menu und Breadcrump einfügen (UI)

### Breadcrumb
- [x] Breadcrumb Komponent erstellen
- [x] Einfügen in Layout: links oben direkt unter neuen Trennbalken
- [x] Erstellen von einem Beispiel für die Übergabe von Daten an Breadcrumb:  Übergabe als Array mit Label und Link
- [x] Hinzufügen eines "Fragezeichen icons" hinter letzten Breadcrumb Eintrag:  rund umrandet,  mit einem tooltip;  Inhalt wird durch eine eigene (neue) variable übergeben ("page_info").
- [x] Hinzufügen von zusätzlichen Links: rechten Seite in der breadcrumb Zeile; Übergabe auch durch Variable ("page_links")

## Content
- [x] 3 Bereiche (Slots): left, middle = default, right
- [x] right und left haben eine fixe Breite in rem nicht Pixel. Kein Inhalt -> Kein Platz see: https://dev.to/danawoodman/svelte-quick-tip-styling-conditional-named-slots-4817
- [x] zentriere den middle slot 

## Footer
- [x] erstelle eine default footer html (absprache mit sven wo die dateien abgelegt werden sollen, eventl in den tenants)
- [x] lade die default footer html vom backend und rendere sie in der Page-Componente

# Board Notes
![image](https://github.com/BEXIS2/bexis2-core-ui/assets/19665289/a1242b5f-e73c-4678-8528-9546f55c52b2)

----

# Page Layout Besprechung

es wird in der version 2 Layout Pages geben. Eine ist für die alten Seiten und eine für die neuen.
- das Layout der alten seiten findet an -> **Console/BExIS.Web.Shell/Themes/Default/Layouts/_Layout.cshtml**
- das neue Layout wird die Page Component in @bexis2/bexis2-core-ui

> wichtig! die Aufgabe ist erst erledigt, wenn sowohl die Layout im **Core** als auch in der UI Libary erledigt ist. Anpassungen sind auf beiden seiten nötig. Für den Anfang sind aber die Anpassungen in der UI Libary wichtig.

- Aufgaben für das Backend werden mit **Core** getaggt
- Aufgaben für @bexis2/bexis2-core-ui werden mit UI getaggt

## Header und Menu
- wir haben uns abgesprochen, dass der Header einen Custom-Bereich bekommt, den jede Instanz für sich definieren kann. Dafür soll über die Settings möglich sein eine Header Html hochzuladen und im Header-Bereich gerendert werden.  
- Ein Default Header ist nötig. 
- Im Fall von IDiv und BEXIS kann der Custom Header dazu genutzt werden, um ein Großen Logo und dem Titel angeziegt werden.
- das Menu (auch settings) und Platz für ein kleines Logo werden in einer Zeile umgesetzt

## Footer 
- eben so wie der Header soll es möglich sein, eine Footer Html bereit zu stellen und diese soll dann an der footer stelle gerendert werden
- hier ist ein Default Footer nötig

## Breadcrump
- direkt unterhalb des menus soll an der linken Seite ein Breadcrump erstellt werden.
- Die Breakcrump informationen werden der Page übergeben, Array mit label und link?
- direkt nach dem breadcrumd soll ein fragenzeichen icon gesetzt werden, als tooltip sollen da die Informationen aus dem note oder description angezeigt werden. start erstmal mit note
- auf der rechten seite auf der gleichen höhe, sollten die links angezeigt werden -> vielleich kann man bei manuals ein buch anzeigen oder man reduziert es nur auf einem link direkt für manual

## Content
- wir brauchen 3 Bereiche die über slots von außen gesetzt werden müssen
- left, right, middle
- middle braucht keine id, default slot
- der inhalt im default slot sollte immer centered im bezug auf die breite sein
- left und right braucht fixe breite muss aber kleiner werden
- wenn kein inhalt in left oder right, dann soll middle über die ganze Seite gehen

## generell
- die seite muss auf einen Monitor und auf einem smartphone funktionieren
- slots müssen sich ab eine bestimmten größe anderst verhalten,

**Comment by DavidBlaa** [comment]
- i am not happy with the situtaion if left not exist start directly from left.
we need to discuss this again
